### PR TITLE
Security: run scripts as non-root user

### PR DESCRIPTION
**Pull request by danielparks**
These scripts don't need to be run as root; run them as a new system user called `pe_metric_curl_cron_jobs` instead.

This enforces ownership for a number of files to ensure they're not writable by the scripts. It also moves the scripts directory out of the output directory to ensure that directory tree below scripts is not writable by the `pe_metric_curl_cron_jobs` user.

### CODE REVIEW

**Comment by danielparks** [comment]
I've got another change coming after this one is merged. :)

**Comment by npwalker** [comment]
@danielparks what's the behavior of this change if you install the current version and then upgrade to this version?  I'd want to make sure that no files are left in old paths.  

Other than that it sounds like a good idea.

**Comment by danielparks** [comment]
Good point. I've updated and tested this.

**Comment by npwalker** [comment]
@danielparks I'm not sure the output_dir needs to be moved since files aren't actually put in the output_dir ( poorly named). they are put in the metrics_output_dir.  

https://github.com/npwalker/pe_metric_curl_cron_jobs/blob/master/manifests/pe_metric.pp#L15

The layout looking like:

```
[root@master201648-centos pe_metric_curl_cron_jobs]# ls -ll /opt/puppetlabs/pe_metric_curl_cron_jobs/
total 20
drwxr-xr-x. 3 root root 4096 Oct 18 19:41 activemq
drwxr-xr-x. 3 root root 4096 Oct 18 19:41 orchestrator
drwxr-xr-x. 3 root root 4096 Oct 18 02:40 puppetdb
drwxr-xr-x. 3 root root 4096 Oct 18 22:42 puppetserver
drwxr-xr-x. 2 root root 4096 Oct 18 22:37 scripts
```

If we move the output_dir then we lose the history for the metrics that have already been collected and that's not a good option since we like trending data.  

Is there a way to avoid moving the output_dir?

**Comment by danielparks** [comment]
Sure. We could move the scripts directory somewhere else. The issue is that the scripts directory should not be in the output directory.

**Comment by npwalker** [comment]
@danielparks What I'm trying to say is that output ( metrics files in this case ) is written to each individual directory for the component.  i.e. puppetserver or puppetdb.  Nothing is actually written to `/opt/puppetlabs/pe_metric_curl_cron_jobs`.  

What I'm trying to understand is if we can fix the permissions on each component level directory and leave the directory structure the same?  It's unclear to me how making an `output` directory changes what needs to happen.  `output` would be at the same level as `scripts` the same way each component level directory is at the same level as scripts.  

The only thing I can see is that you've set the home directory for the [new user to the output dir](https://github.com/npwalker/pe_metric_curl_cron_jobs/pull/44/files#diff-60ae41fd0a31977447947f59940ee9a4R27).  Is that the major sticking point?

**Comment by danielparks** [comment]
Ah, I see. I misunderstood where output files were created. I've moved them back into the original location.

I haven't had a chance to test this yet.

**Pull request closed without merging**
