### PR TITLE
Move script configuration into a YAML file

### PR DESCRIPTION
**Pull request by npwalker**
Prior to this PR, we passed variables from Puppet into the ruby script by interpolating them into the ruby script during a Puppet run.  

After this PR, we place the variables from Puppet into a YAML file that can be read by the ruby script when it is run.  This opens the door to using the script outside of the scope of Puppet.  It makes the `--metrics_type` argument to the metrics_script mandatory so that the ruby script knows where to load it's configuration from.

### CODE REVIEW

**Comment by acidprime** [comment]
:+1: Have not tested but the code looks good to me, any reason not to move it out of an templates and into files now that there is no interpolation? Might encourage people not to add it back in in the future .

**Comment by npwalker** [comment]
@acidprime yea I was going to do that next.  I just like to make small changes and ensure they work.  And it is done https://github.com/npwalker/pe_metric_curl_cron_jobs/pull/25/commits/f6c8e82fe909d578f78d8611f5b01f44f90ac2b7

**Review by reidmv — APPROVED** [review]
I like it. This gets us a step closer to having a stand-alone script to perform the metrics gathering.

As long as we reserve the right to change details of the config file interface in future iterations (treat the config file as a private API for now), I'm 👍 .

**Comment by npwalker** [comment]
@reidmv This literally does give us a stand-alone script, assuming you provide a config file to run it.  Since the config file is currently managed completely by Puppet, I do consider it to be private.  There's no way to stop Puppet from managing it at this time so I think we can change it up until we give people the ability to not manage the config file.

**Comment by jarretlavallee** [comment]
👍  Looks good to me. It works on LTS and 2017.1.1.

**Pull request merged**
