### PR TITLE
Pull the PuppetDB status endpoint for consistent queue_depth metric

### PR DESCRIPTION
**Pull request by npwalker**
Prior to this commit, we used ActiveMQ metrics to find the queue
depth metric and then in 2017.1 we used a specific metric from
PuppetDB.  However, the status endpoint has a queue_depth metric
in it that correctly chooses the backend depending on version.

After this commit, we will only track the status endpoint and not
the specific queue depth metric so that we can look at the same
metric across versions.

### CODE REVIEW

**Comment by npwalker** [comment]
Looks like this: 

2017.1

~~~
[root@master201710-centos pe_metric_curl_cron_jobs]# cat /opt/puppetlabs/pe_metric_curl_cron_jobs/puppetdb/127.0.0.1/20170320T153159Z.json 
{
  "timestamp": "2017-03-20T15:31:59Z",
  "servers": {
    "127-0-0-1": {
      "puppetdb": {
        "puppetdb-status": {
          "service_version": "4.3.2",
          "service_status_version": 1,
          "detail_level": "debug",
          "state": "running",
          "status": {
            "maintenance_mode?": false,
            "queue_depth": 0,
            "read_db_up?": true,
            "write_db_up?": true,
            "rbac_status": "running",
            "sync_status": {
              "state": "idle"
            }
          },
          "active_alerts": [

          ]
        },
        "status-service": {
          "service_version": "0.5.0",
          "service_status_version": 1,
          "detail_level": "debug",
          "state": "running",
          "status": {
            "experimental": {
              "jvm-metrics": {
                "heap-memory": {
                  "committed": 134217728,
                  "init": 134217728,
                  "max": 134217728,
                  "used": 79032296
                },
                "non-heap-memory": {
                  "committed": 279265280,
                  "init": 2555904,
                  "max": -1,
                  "used": 180227744
                },
                "up-time-ms": 320833351,
                "start-time-ms": 1489703086663
              }
            }
          },
          "active_alerts": [

          ]
        },
        "command_processing_time": {
          "OneMinuteRate": 0.0003452298710984832,
          "MeanRate": 0.0016551647304778932,
          "FifteenMinuteRate": 0.002764956209338259,
          "Max": 327.51516499999997,
          "50thPercentile": 188.108262,
          "Mean": 170.19662896468802,
          "DurationUnit": "milliseconds",
          "95thPercentile": 232.428735,
          "99thPercentile": 232.428735,
          "98thPercentile": 232.428735,
          "Min": 57.762597,
          "999thPercentile": 232.428735,
          "RateUnit": "events/second",
          "75thPercentile": 232.428735,
          "Count": 531,
          "StdDev": 70.8610150554319,
          "FiveMinuteRate": 0.0036997286102142483
        },
        "command_processed": {
          "RateUnit": "events/second",
          "Count": 531,
          "FifteenMinuteRate": 0.002764956209338259,
          "FiveMinuteRate": 0.0036997286102142483,
          "MeanRate": 0.0016551641285444858,
          "OneMinuteRate": 0.0003452298710984832
        },
        "catalog_hash_miss": {
          "OneMinuteRate": 0.0,
          "MeanRate": 0.0,
          "FifteenMinuteRate": 0.0,
          "Max": 0.0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "DurationUnit": "milliseconds",
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0.0,
          "999thPercentile": 0.0,
          "RateUnit": "events/second",
          "75thPercentile": 0.0,
          "Count": 0,
          "StdDev": 0.0,
          "FiveMinuteRate": 0.0
        },
        "catalog_hash_match": {
          "OneMinuteRate": 0.0001077472993017049,
          "MeanRate": 0.0005517178146636299,
          "FifteenMinuteRate": 0.000918203852399271,
          "Max": 9.549069,
          "50thPercentile": 1.242244,
          "Mean": 1.2422440000003363,
          "DurationUnit": "milliseconds",
          "95thPercentile": 1.242244,
          "99thPercentile": 1.242244,
          "98thPercentile": 1.242244,
          "Min": 1.186062,
          "999thPercentile": 1.242244,
          "RateUnit": "events/second",
          "75thPercentile": 1.242244,
          "Count": 177,
          "StdDev": 2.4533587042614593e-07,
          "FiveMinuteRate": 0.001219124373490364
        },
        "replace_catalog_time": {
          "OneMinuteRate": 0.0001077472993017049,
          "MeanRate": 0.0005517176000854618,
          "FifteenMinuteRate": 0.000918203852399271,
          "Max": 204.434258,
          "50thPercentile": 149.049656,
          "Mean": 149.04965599993818,
          "DurationUnit": "milliseconds",
          "95thPercentile": 149.049656,
          "99thPercentile": 149.049656,
          "98thPercentile": 149.049656,
          "Min": 102.406176,
          "999thPercentile": 149.049656,
          "RateUnit": "events/second",
          "75thPercentile": 149.049656,
          "Count": 177,
          "StdDev": 4.509012048469087e-05,
          "FiveMinuteRate": 0.001219124373490364
        },
        "replace_facts_time": {
          "OneMinuteRate": 9.120611976521244e-05,
          "MeanRate": 0.0005517174128864797,
          "FifteenMinuteRate": 0.0009080580572814383,
          "Max": 109.681562,
          "50thPercentile": 55.707573,
          "Mean": 55.70757300010001,
          "DurationUnit": "milliseconds",
          "95thPercentile": 55.707573,
          "99thPercentile": 55.707573,
          "98thPercentile": 55.707573,
          "Min": 52.876104999999995,
          "999thPercentile": 55.707573,
          "RateUnit": "events/second",
          "75thPercentile": 55.707573,
          "Count": 177,
          "StdDev": 7.295159006510206e-05,
          "FiveMinuteRate": 0.0011791567225299187
        },
        "store_report_time": {
          "OneMinuteRate": 0.0001383502708828504,
          "MeanRate": 0.0005517171949962163,
          "FifteenMinuteRate": 0.0009336354897046307,
          "Max": 104.816581,
          "50thPercentile": 91.05179,
          "Mean": 91.05178999998236,
          "DurationUnit": "milliseconds",
          "95thPercentile": 91.05179,
          "99thPercentile": 91.05179,
          "98thPercentile": 91.05179,
          "Min": 44.388393,
          "999thPercentile": 91.05179,
          "RateUnit": "events/second",
          "75thPercentile": 91.05179,
          "Count": 177,
          "StdDev": 1.2867384648833954e-05,
          "FiveMinuteRate": 0.0012816302167379483
        },
        "global_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FifteenMinuteRate": 0.0,
          "FiveMinuteRate": 0.0,
          "MeanRate": 0.0,
          "OneMinuteRate": 0.0
        },
        "global_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 531,
          "StdDev": 0.0
        },
        "replace_catalog_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FifteenMinuteRate": 0.0,
          "FiveMinuteRate": 0.0,
          "MeanRate": 0.0,
          "OneMinuteRate": 0.0
        },
        "replace_catalog_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 177,
          "StdDev": 0.0
        },
        "replace_facts_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FifteenMinuteRate": 0.0,
          "FiveMinuteRate": 0.0,
          "MeanRate": 0.0,
          "OneMinuteRate": 0.0
        },
        "replace_facts_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 177,
          "StdDev": 0.0
        },
        "store_report_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FifteenMinuteRate": 0.0,
          "FiveMinuteRate": 0.0,
          "MeanRate": 0.0,
          "OneMinuteRate": 0.0
        },
        "store_reports_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 177,
          "StdDev": 0.0
        },
        "error": [

        ],
        "error_count": 0,
        "api-query-start": "2017-03-20T15:31:59Z",
        "api-query-duration": 1.905894025
      }
    }
  }
}
~~~

2016.4

~~~
[root@master201644-centos pe_metric_curl_cron_jobs]# cat /opt/puppetlabs/pe_metric_curl_cron_jobs/puppetdb/127.0.0.1/20170320T153443Z.json 
{
  "timestamp": "2017-03-20T15:34:43Z",
  "servers": {
    "127-0-0-1": {
      "puppetdb": {
        "puppetdb-status": {
          "service_version": "4.2.3.1",
          "service_status_version": 1,
          "detail_level": "debug",
          "state": "running",
          "status": {
            "maintenance_mode?": false,
            "queue_depth": 0,
            "read_db_up?": true,
            "write_db_up?": true,
            "rbac_status": "running",
            "sync_status": {
              "state": "idle"
            }
          },
          "active_alerts": [

          ]
        },
        "status-service": {
          "service_version": "0.4.0",
          "service_status_version": 1,
          "detail_level": "debug",
          "state": "running",
          "status": {
            "experimental": {
              "jvm-metrics": {
                "heap-memory": {
                  "committed": 134217728,
                  "init": 134217728,
                  "max": 134217728,
                  "used": 113459032
                },
                "non-heap-memory": {
                  "committed": 279437312,
                  "init": 2555904,
                  "max": -1,
                  "used": 180340888
                },
                "up-time-ms": 599255150,
                "start-time-ms": 1489424828183
              }
            }
          },
          "active_alerts": [

          ]
        },
        "amq_metrics": {
          "DequeueCount": 3,
          "MinMessageSize": 10860,
          "AverageEnqueueTime": 11.333333333333334,
          "DispatchCount": 3,
          "SlowConsumerStrategy": null,
          "ProducerCount": 0,
          "MessageGroups": {
          },
          "MaxMessageSize": 1099081,
          "AverageBlockedTime": 0.0,
          "ForwardCount": 0,
          "MinEnqueueTime": 5,
          "MaxProducersToAudit": 1024,
          "InFlightCount": 0,
          "MemoryPercentUsage": 0,
          "UseCache": true,
          "AlwaysRetroactive": false,
          "CacheEnabled": true,
          "TotalBlockedTime": 0,
          "MaxPageSize": 200,
          "CursorMemoryUsage": 0,
          "BlockedProducerWarningInterval": 30000,
          "MaxEnqueueTime": 16,
          "MemoryLimit": 93952410,
          "MaxAuditDepth": 2048,
          "QueueSize": 0,
          "Options": "",
          "EnqueueCount": 3,
          "MemoryUsagePortion": 1.0,
          "ExpiredCount": 0,
          "CursorFull": false,
          "Name": "puppetlabs.puppetdb.commands",
          "ProducerFlowControl": true,
          "DLQ": false,
          "StoreMessageSize": 0,
          "Paused": false,
          "PrioritizedMessages": false,
          "AverageMessageSize": 501895,
          "Subscriptions": "[Ljavax.management.ObjectName;@78110443",
          "CursorPercentUsage": 0,
          "ConsumerCount": 2,
          "MessageGroupType": "cached",
          "MemoryUsageByteCount": 0,
          "BlockedSends": 0
        },
        "command_processing_time": {
          "OneMinuteRate": 2.964393875e-314,
          "MeanRate": 5.006417675228803e-06,
          "FifteenMinuteRate": 1.6539654674926284e-291,
          "Max": 953.0729739999999,
          "50thPercentile": 475.189327,
          "Mean": 602.8149081677853,
          "DurationUnit": "milliseconds",
          "95thPercentile": 953.0729739999999,
          "99thPercentile": 953.0729739999999,
          "98thPercentile": 953.0729739999999,
          "Min": 390.43219999999997,
          "999thPercentile": 953.0729739999999,
          "RateUnit": "events/second",
          "75thPercentile": 953.0729739999999,
          "Count": 3,
          "StdDev": 240.56142388027644,
          "FiveMinuteRate": 1.4821969375e-313
        },
        "command_processed": {
          "RateUnit": "events/second",
          "Count": 3,
          "FiveMinuteRate": 1.4821969375e-313,
          "OneMinuteRate": 2.964393875e-314,
          "FifteenMinuteRate": 1.6539654674926284e-291,
          "MeanRate": 5.006416807227524e-06
        },
        "catalog_hash_miss": {
          "OneMinuteRate": 2.964393875e-314,
          "MeanRate": 1.6687988495270124e-06,
          "FifteenMinuteRate": 5.502659136260797e-292,
          "Max": 474.068645,
          "50thPercentile": 474.068645,
          "Mean": 474.068645,
          "DurationUnit": "milliseconds",
          "95thPercentile": 474.068645,
          "99thPercentile": 474.068645,
          "98thPercentile": 474.068645,
          "Min": 474.068645,
          "999thPercentile": 474.068645,
          "RateUnit": "events/second",
          "75thPercentile": 474.068645,
          "Count": 1,
          "StdDev": 0.0,
          "FiveMinuteRate": 1.4821969375e-313
        },
        "catalog_hash_match": {
          "OneMinuteRate": 0.0,
          "MeanRate": 0.0,
          "FifteenMinuteRate": 0.0,
          "Max": 0.0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "DurationUnit": "milliseconds",
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0.0,
          "999thPercentile": 0.0,
          "RateUnit": "events/second",
          "75thPercentile": 0.0,
          "Count": 0,
          "StdDev": 0.0,
          "FiveMinuteRate": 0.0
        },
        "replace_catalog_time": {
          "OneMinuteRate": 2.964393875e-314,
          "MeanRate": 1.6687981279999805e-06,
          "FifteenMinuteRate": 5.502659136260797e-292,
          "Max": 858.853407,
          "50thPercentile": 858.853407,
          "Mean": 858.853407,
          "DurationUnit": "milliseconds",
          "95thPercentile": 858.853407,
          "99thPercentile": 858.853407,
          "98thPercentile": 858.853407,
          "Min": 858.853407,
          "999thPercentile": 858.853407,
          "RateUnit": "events/second",
          "75thPercentile": 858.853407,
          "Count": 1,
          "StdDev": 0.0,
          "FiveMinuteRate": 1.4821969375e-313
        },
        "replace_facts_time": {
          "OneMinuteRate": 2.964393875e-314,
          "MeanRate": 1.6687978312390315e-06,
          "FifteenMinuteRate": 5.472173568268668e-292,
          "Max": 338.368997,
          "50thPercentile": 338.368997,
          "Mean": 338.368997,
          "DurationUnit": "milliseconds",
          "95thPercentile": 338.368997,
          "99thPercentile": 338.368997,
          "98thPercentile": 338.368997,
          "Min": 338.368997,
          "999thPercentile": 338.368997,
          "RateUnit": "events/second",
          "75thPercentile": 338.368997,
          "Count": 1,
          "StdDev": 0.0,
          "FiveMinuteRate": 1.4821969375e-313
        },
        "store_report_time": {
          "OneMinuteRate": 2.964393875e-314,
          "MeanRate": 1.6687975457936835e-06,
          "FifteenMinuteRate": 5.626309252136063e-292,
          "Max": 139.381555,
          "50thPercentile": 139.381555,
          "Mean": 139.381555,
          "DurationUnit": "milliseconds",
          "95thPercentile": 139.381555,
          "99thPercentile": 139.381555,
          "98thPercentile": 139.381555,
          "Min": 139.381555,
          "999thPercentile": 139.381555,
          "RateUnit": "events/second",
          "75thPercentile": 139.381555,
          "Count": 1,
          "StdDev": 0.0,
          "FiveMinuteRate": 1.4821969375e-313
        },
        "global_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FiveMinuteRate": 0.0,
          "OneMinuteRate": 0.0,
          "FifteenMinuteRate": 0.0,
          "MeanRate": 0.0
        },
        "global_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 3,
          "StdDev": 0.0
        },
        "replace_catalog_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FiveMinuteRate": 0.0,
          "OneMinuteRate": 0.0,
          "FifteenMinuteRate": 0.0,
          "MeanRate": 0.0
        },
        "replace_catalog_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 1,
          "StdDev": 0.0
        },
        "replace_facts_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FiveMinuteRate": 0.0,
          "OneMinuteRate": 0.0,
          "FifteenMinuteRate": 0.0,
          "MeanRate": 0.0
        },
        "replace_facts_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 1,
          "StdDev": 0.0
        },
        "store_report_retried": {
          "RateUnit": "events/second",
          "Count": 0,
          "FiveMinuteRate": 0.0,
          "OneMinuteRate": 0.0,
          "FifteenMinuteRate": 0.0,
          "MeanRate": 0.0
        },
        "store_reports_retry_counts": {
          "Max": 0,
          "50thPercentile": 0.0,
          "Mean": 0.0,
          "95thPercentile": 0.0,
          "99thPercentile": 0.0,
          "98thPercentile": 0.0,
          "Min": 0,
          "999thPercentile": 0.0,
          "75thPercentile": 0.0,
          "Count": 1,
          "StdDev": 0.0
        },
        "error": [

        ],
        "error_count": 0,
        "api-query-start": "2017-03-20T15:34:43Z",
        "api-query-duration": 2.50935212
      }
    }
  }
}
~~~

**Comment by npwalker** [comment]
@jarretlavallee @reidmv if you'd all like to play around with this change I'd appreciate it.  The main purpose was to start tracking the puppetdb status endpoint because the queue_depth metric there will alleviate the need to remember which metric to graph in graphana, you'll just use the one from the status endpoint. 

Upon completing that work, I realized the puppetdb script was just more versatile than the puppetserver script and I decided to combine them into one which is good because they had subtle differences that this change gets rid of.

**Comment by jarretlavallee** [comment]
I like that both scripts were combined as it simplifies the code base and makes it easier to maintain. I am playing with this now and have found the code to functional across the base testing.  2016.5.2 is consistent with the results in 2016.4.3 and 2017.1 as well. 

As a side effect/intentional change of the combination of the puppetserver and puppetdb scripts, the errors are all in an array. This fixes an issue of consistency across error output in the previous versions.

**Comment by reidmv** [comment]
I'm 👍 for the idea of unifying work into common modules, but I'm 👎 for making a template that _actually_ contains multiple logical scripts and builds into those different scripts based on parameters. The more logic goes into a template the harder it is to maintain, and the harder it is to understand what the template does just by reading it.

I would strongly prefer keeping separate, simple templates OR switching to a shared, non-template script/library that small templatized files can then incorporate.

Relevant: see #14. ActiveMQ does not use a trapperkeeper status endpoint but we want to be able to gather those metrics. This would be easy to do with a common shared library AND an individual small template. It would be a mess to try and incorporate that into a single unified template with PuppetDB and Puppetserver collection.

**Comment by npwalker** [comment]
@reidmv I think the ActiveMQ metrics are a one-off so they will be different probably no matter what we do.  

I do think we can take the existing script and break it apart a bit, make actual arguments and pass those in instead of hard coding them on top via the template.  I'm all for that but I wasn't sure how to do it immediately and I don't think it's immediately necessary.   I think it can be broken apart in a .z release if we wanted since it won't change the functionality of the module just make it easier to maintain.  

I propose we merge this and then proceed with a new PR to break things apart and make them more maintainable.  Essentially make arguments to the script and also move the metrics hash out of the template to be passed in as an argument.

**Comment by reidmv** [comment]
I think ActiveMQ makes this a bigger deal than it would be if we only wanted to monitor PuppetDB and Puppetserver. And the ActiveMQ work is ready to go, now.

Because ActiveMQ IS different and this PR assumes every instance of `pe_metric_curl_cron_jobs::pe_metric` uses the same template (https://github.com/npwalker/pe_metric_curl_cron_jobs/blob/fa12e32075cd27a7358c6e33e1e5cc8334f63747/manifests/pe_metric.pp#L26), merging this PR would mean we DO have to break this into a library immediately, as not doing so becomes a blocker to monitoring ActiveMQ.

I think the main benefit of #13 can be characterized as code hygiene, yes? That and some consistency improvements to error collecting.

ActiveMQ/MCollective monitoring is a bigger win than code hygiene and error format. For that reason I would suggest merging #14 instead, and THEN doing the break-apart work, doing it right, to gain back hygiene and consistency.

@npwalker your call to make. Whichever direction we go first we'll then move on to the other work, time permitting.

**Comment by reidmv** [comment]
Maybe this point should be clarified, actually:

There are two commits in this PR.

bed6a99991da69bc3e44674b716253dff62b3364 is the titular commit, and provides a consistent queue_depth metric. This commit can easily be merged.

fa12e32075cd27a7358c6e33e1e5cc8334f63747 has nothing to do with the title and is a hygiene, consistency refactor. This is what I believe conflicts with #14 and what should not be merged now.

**Comment by npwalker** [comment]
@reidmv okay I added a commit ( https://github.com/npwalker/pe_metric_curl_cron_jobs/pull/13/commits/f3824a937d9075cbbcf0441ccb0a638f6671a456 ) to allow choosing your metric script template.  This means the activemq addition can set it's own script template and we can still consolidate.  Let me know what you think.

**Pull request merged**
